#!/bin/bash
# /etc/init.d/servoblaster

### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to manage a servo
### END INIT INFO


case "$1" in 
    start)
        echo "Starting servoblaster"
        /home/pi/servoblaster/PiBits/ServoBlaster/user/servod
        ;;
    stop)
        echo "Stopping servoblaster"
        killall servod
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac

exit 0